server:
  port: 3306
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 1h					
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@//211.238.142.123/xe
    hikari:
      username: SAPIENS
      password: java1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

