-- 노쇼 시 매너온도 1점 차감 프로시저
CREATE OR REPLACE PROCEDURE SP_INSERT_NOSHOW(
	P_USER_ID  IN  NUMBER
  , P_NEW_TEMP OUT NUMBER
)
IS

BEGIN      
        INSERT INTO MANNER_HISTORY (MANNER_HISTORY_ID, USER_ID, REASON_ID, SCORE)
        VALUES (MANNER_HISTORY_SEQ.NEXTVAL, P_USER_ID, 1, -1);
        
        P_NEW_TEMP := FN_GET_MANNER(P_USER_ID);
END;
/


-- 활성 매니저 조회 뷰 
  CREATE OR REPLACE VIEW V_ACTIVE_MANAGER AS
  SELECT mh.MANAGER_HISTORY_ID, mh.CAFE_ID, mh.USER_ID,
         mh.CREATED_AT,
         c.USER_ID  AS OWNER_USER_ID,   -- 사장 검색용 (c.USER_ID가 카페 소유주)
         c.CAFE_NAME,
         ua.LOGIN_ID, ua.NICKNAME,
         ui.PHONE
    FROM MANAGER_HISTORY mh
    JOIN CAFE         c  ON c.CAFE_ID  = mh.CAFE_ID
    JOIN USER_ACCOUNT ua ON ua.USER_ID = mh.USER_ID
    LEFT JOIN USER_INFO ui ON ui.USER_ID = mh.USER_ID
   WHERE mh.MANAGER_HISTORY_ID IN (
         SELECT MAX(MANAGER_HISTORY_ID) FROM MANAGER_HISTORY GROUP BY CAFE_ID, USER_ID
     )
     AND mh.REG_EVENT_ID = 1;