SELECT USER
FROM DUAL;


CREATE SEQUENCE GRADE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMMON_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE;
CREATE SEQUENCE REG_EVENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE USER_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ADMIN_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ADMIN_INFO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ADMIN_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CAFE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CAFE_DROP_REASON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CAFE_DROP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ROOM_GENRE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ROOM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ROOM_DROP_REASON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ROOM_DROP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MANAGER_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RES_OPEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RES_DROP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MANNER_REASON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MANNER_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE GENDER_CONDITION_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE;
CREATE SEQUENCE PARTY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARTY_ROOM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARTY_DROP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARTY_APPLY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARTY_MEMBER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARTY_KICK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARTY_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_DELETE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RESERVATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RESERVATION_CANCEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ATTEND_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ATTENDANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ATTENDANCE_DETAIL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RECORD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE REVIEW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MUTUAL_EVALUATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EVAL_QUESTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EVAL_ANSWER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;



-- ===================================================================
--○  시퀀스 일괄 삭제
-- ===================================================================

DROP SEQUENCE GRADE_SEQ;
DROP SEQUENCE COMMON_SEQ;
DROP SEQUENCE REG_EVENT_SEQ;
DROP SEQUENCE USER_ACCOUNT_SEQ;
DROP SEQUENCE ADMIN_ACCOUNT_SEQ;
DROP SEQUENCE ADMIN_INFO_SEQ;
DROP SEQUENCE ADMIN_HISTORY_SEQ;
DROP SEQUENCE CAFE_SEQ;
DROP SEQUENCE CAFE_DROP_REASON_SEQ;
DROP SEQUENCE CAFE_DROP_SEQ;
DROP SEQUENCE ROOM_GENRE_SEQ;
DROP SEQUENCE ROOM_SEQ;
DROP SEQUENCE ROOM_DROP_REASON_SEQ;
DROP SEQUENCE ROOM_DROP_SEQ;
DROP SEQUENCE MANAGER_HISTORY_SEQ;
DROP SEQUENCE RES_OPEN_SEQ;
DROP SEQUENCE RES_DROP_SEQ;
DROP SEQUENCE MANNER_REASON_SEQ;
DROP SEQUENCE MANNER_HISTORY_SEQ;
DROP SEQUENCE GENDER_CONDITION_SEQ;
DROP SEQUENCE PARTY_SEQ;
DROP SEQUENCE PARTY_ROOM_SEQ;
DROP SEQUENCE PARTY_DROP_SEQ;
DROP SEQUENCE PARTY_APPLY_SEQ;
DROP SEQUENCE PARTY_MEMBER_SEQ;
DROP SEQUENCE PARTY_KICK_SEQ;
DROP SEQUENCE PARTY_MESSAGE_SEQ;
DROP SEQUENCE MESSAGE_DELETE_SEQ;
DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE RESERVATION_CANCEL_SEQ;
DROP SEQUENCE ATTEND_STATUS_SEQ;
DROP SEQUENCE ATTENDANCE_SEQ;
DROP SEQUENCE ATTENDANCE_DETAIL_SEQ;
DROP SEQUENCE RECORD_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE MUTUAL_EVALUATION_SEQ;
DROP SEQUENCE EVAL_QUESTION_SEQ;
DROP SEQUENCE EVAL_ANSWER_SEQ;




-- 1. GRADE
CREATE TABLE GRADE (
    GRADE_ID NUMBER,
    GRADE_NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_GRADE PRIMARY KEY (GRADE_ID),
    CONSTRAINT UK_GRADE_NAME UNIQUE (GRADE_NAME)
);
--COMMENT ON COLUMN GRADE.GRADE_NAME IS '1점, 2점, 3점, 4점, 5점';

-- 2. COMMON
CREATE TABLE COMMON (
    COMMON_ID NUMBER,
    COMMON_NAME CHAR(1) NOT NULL,
    CONSTRAINT PK_COMMON PRIMARY KEY (COMMON_ID),
    CONSTRAINT UK_COMMON_NAME UNIQUE (COMMON_NAME)
);
--COMMENT ON COLUMN COMMON.COMMON_NAME IS 'Y, N';

-- 3. REG_EVENT
CREATE TABLE REG_EVENT (
    REG_EVENT_ID NUMBER,
    REG_EVENT_NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_REG_EVENT PRIMARY KEY (REG_EVENT_ID),
    CONSTRAINT UK_REG_EVENT_NAME UNIQUE (REG_EVENT_NAME)
);
--COMMENT ON COLUMN REG_EVENT.REG_EVENT_NAME IS '등록, 해제';

-- 4. USER_ACCOUNT
CREATE TABLE USER_ACCOUNT (
    USER_ID NUMBER,
    LOGIN_ID VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(500) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_USER_NICKNAME UNIQUE (NICKNAME)
);
--COMMENT ON COLUMN USER_ACCOUNT.LOGIN_ID IS '6글자이상 15글자이하';
--COMMENT ON COLUMN USER_ACCOUNT.PASSWORD IS '암호화';
--COMMENT ON COLUMN USER_ACCOUNT.NICKNAME IS '2글자이상 10글자이하';

-- 5. ADMIN_ACCOUNT
CREATE TABLE ADMIN_ACCOUNT (
    ADMIN_ID NUMBER,
    LOGIN_ID VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_ADMIN_ACCOUNT PRIMARY KEY (ADMIN_ID),
    CONSTRAINT UK_ADMIN_LOGIN_ID UNIQUE (LOGIN_ID)
);
--COMMENT ON COLUMN ADMIN_ACCOUNT.LOGIN_ID IS '6글자이상 15글자이하';
--COMMENT ON COLUMN ADMIN_ACCOUNT.PASSWORD IS 'encrypted';

-- 6. ADMIN_INFO
CREATE TABLE ADMIN_INFO (
    ADMIN_INFO_ID NUMBER,
    NAME VARCHAR2(50) NOT NULL,
    PHONE CHAR(11) NOT NULL,
    CONSTRAINT PK_ADMIN_INFO PRIMARY KEY (ADMIN_INFO_ID)
);
--COMMENT ON COLUMN ADMIN_INFO.PHONE IS '하이픈없이 저장';

-- 7. CAFE_DROP_REASON
CREATE TABLE CAFE_DROP_REASON (
    DROP_REASON_ID NUMBER,
    DROP_REASON_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CAFE_DROP_REASON PRIMARY KEY (DROP_REASON_ID),
    CONSTRAINT UK_CAFE_DROP_REASON_NAME UNIQUE (DROP_REASON_NAME)
);
--COMMENT ON COLUMN CAFE_DROP_REASON.DROP_REASON_NAME IS '폐업, 사업자등록번호오류, 사용자신고';

-- 8. ROOM_GENRE
CREATE TABLE ROOM_GENRE (
    GENRE_ID NUMBER,
    GENRE_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ROOM_GENRE PRIMARY KEY (GENRE_ID),
    CONSTRAINT UK_ROOM_GENRE_NAME UNIQUE (GENRE_NAME)
);
--COMMENT ON COLUMN ROOM_GENRE.GENRE_NAME IS '공포, SF, 스릴러, 드라마, 미스터리, 감성';

-- 9. ROOM_DROP_REASON
CREATE TABLE ROOM_DROP_REASON (
    DROP_REASON_ID NUMBER,
    DROP_REASON_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ROOM_DROP_REASON PRIMARY KEY (DROP_REASON_ID),
    CONSTRAINT UK_ROOM_DROP_REASON_NAME UNIQUE (DROP_REASON_NAME)
);
--COMMENT ON COLUMN ROOM_DROP_REASON.DROP_REASON_NAME IS '부적절한 항목내용, 방폐쇄';

-- 10. MANNER_REASON
CREATE TABLE MANNER_REASON (
    REASON_ID NUMBER,
    REASON_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_MANNER_REASON PRIMARY KEY (REASON_ID),
    CONSTRAINT UK_MANNER_REASON_NAME UNIQUE (REASON_NAME)
);
--COMMENT ON COLUMN MANNER_REASON.REASON_NAME IS '노쇼, 상호평가, 예약취소';

-- 11. GENDER_CONDITION
CREATE TABLE GENDER_CONDITION (
    GENDER_ID NUMBER,
    GENDER_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_GENDER_CONDITION PRIMARY KEY (GENDER_ID),
    CONSTRAINT UK_GENDER_NAME UNIQUE (GENDER_NAME)
);
--COMMENT ON COLUMN GENDER_CONDITION.GENDER_NAME IS '동일성별, 무관';

-- 12. EVAL_QUESTION
CREATE TABLE EVAL_QUESTION (
    QUESTION_ID NUMBER,
    QUESTION VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_EVAL_QUESTION PRIMARY KEY (QUESTION_ID),
    CONSTRAINT UK_EVAL_QUESTION UNIQUE (QUESTION)
);
--COMMENT ON COLUMN EVAL_QUESTION.QUESTION IS '시간약속잘지켰나요?, 함께플레이하기좋은파티원이었나요?';

-- 13. EVAL_ANSWER
CREATE TABLE EVAL_ANSWER (
    ANSWER_ID NUMBER,
    ANSWER VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_EVAL_ANSWER PRIMARY KEY (ANSWER_ID),
    CONSTRAINT UK_EVAL_ANSWER UNIQUE (ANSWER)
);
--COMMENT ON COLUMN EVAL_ANSWER.ANSWER IS '좋음, 나쁨';

-- 14. ATTEND_STATUS
CREATE TABLE ATTEND_STATUS (
    STATUS_ID NUMBER,
    STATUS_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ATTEND_STATUS PRIMARY KEY (STATUS_ID),
    CONSTRAINT UK_STATUS_NAME UNIQUE (STATUS_NAME)
);
--COMMENT ON COLUMN ATTEND_STATUS.STATUS_NAME IS '출석, 노쇼';

-- 15. USER_INFO
CREATE TABLE USER_INFO (
    USER_ID NUMBER,
    EMAIL VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    PHONE CHAR(11) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    CONSTRAINT PK_USER_INFO PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USER_INFO_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_USER_INFO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USER_INFO_GENDER CHECK (GENDER IN ('F', 'M'))
);
--COMMENT ON COLUMN USER_INFO.PHONE IS '하이픈없이';
--COMMENT ON COLUMN USER_INFO.GENDER IS 'check: F, M';

-- 16. USER_DROP
CREATE TABLE USER_DROP (
    USER_ID NUMBER,
    EMAIL VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    PHONE CHAR(11) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    DROP_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_DROP PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USER_DROP_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_USER_DROP_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USER_DROP_GENDER CHECK (GENDER IN ('F', 'M'))
);
--COMMENT ON COLUMN USER_DROP.PHONE IS '하이픈없이';
--COMMENT ON COLUMN USER_DROP.GENDER IS 'check: F, M';

-- 17. ADMIN_HISTORY
CREATE TABLE ADMIN_HISTORY (
    ADMIN_HISTORY_ID NUMBER,
    ADMIN_ID NUMBER NOT NULL,
    ADMIN_INFO_ID NUMBER NOT NULL,
    START_DATE DATE DEFAULT SYSDATE NOT NULL,
    END_DATE DATE,
    CONSTRAINT PK_ADMIN_HISTORY PRIMARY KEY (ADMIN_HISTORY_ID),
    CONSTRAINT FK_ADMIN_HIST_ADMIN_ID FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN_ACCOUNT(ADMIN_ID),
    CONSTRAINT FK_ADMIN_HIST_INFO_ID FOREIGN KEY (ADMIN_INFO_ID) REFERENCES ADMIN_INFO(ADMIN_INFO_ID)
);

-- 18. CAFE
CREATE TABLE CAFE (
    CAFE_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    BR_NO CHAR(10) NOT NULL,
    CAFE_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    POSTAL_CODE CHAR(5) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(200),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CAFE PRIMARY KEY (CAFE_ID),
    CONSTRAINT FK_CAFE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_CAFE_BR_NO UNIQUE (BR_NO)
);
--COMMENT ON COLUMN CAFE.BR_NO IS '하이픈제외';
--COMMENT ON COLUMN CAFE.PHONE IS 'no hyphen';

-- 19. MANNER_HISTORY
CREATE TABLE MANNER_HISTORY (
    MANNER_HISTORY_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    REASON_ID NUMBER NOT NULL,
    SCORE NUMBER(4,2) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MANNER_HISTORY PRIMARY KEY (MANNER_HISTORY_ID),
    CONSTRAINT FK_MANNER_HIST_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT FK_MANNER_HIST_REASON_ID FOREIGN KEY (REASON_ID) REFERENCES MANNER_REASON(REASON_ID)
);
--COMMENT ON COLUMN MANNER_HISTORY.SCORE IS '양수, 음수';

-- 20. PARTY
CREATE TABLE PARTY (
    PARTY_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    PARTY_NAME VARCHAR2(200) NOT NULL,
    GENDER_ID NUMBER NOT NULL,
    MESSAGE VARCHAR2(4000),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY PRIMARY KEY (PARTY_ID),
    CONSTRAINT FK_PARTY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT FK_PARTY_GENDER_ID FOREIGN KEY (GENDER_ID) REFERENCES GENDER_CONDITION(GENDER_ID)
);
--COMMENT ON COLUMN PARTY.USER_ID IS '파티장';

-- 21. CAFE_DROP
CREATE TABLE CAFE_DROP (
    CAFE_DROP_ID NUMBER,
    CAFE_ID NUMBER NOT NULL,
    DROP_REASON_ID NUMBER,
    DROP_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CAFE_DROP PRIMARY KEY (CAFE_DROP_ID),
    CONSTRAINT FK_CAFE_DROP_CAFE_ID FOREIGN KEY (CAFE_ID) REFERENCES CAFE(CAFE_ID),
    CONSTRAINT FK_CAFE_DROP_REASON_ID FOREIGN KEY (DROP_REASON_ID) REFERENCES CAFE_DROP_REASON(DROP_REASON_ID)
);

-- 22. ROOM
CREATE TABLE ROOM (
    ROOM_ID NUMBER,
    CAFE_ID NUMBER NOT NULL,
    ROOM_NAME VARCHAR2(100) NOT NULL,
    GENRE_ID NUMBER NOT NULL,
    DURATION NUMBER NOT NULL,
    DIFFICULTY NUMBER NOT NULL,
    HORROR_GRADE NUMBER NOT NULL,
    ACTIVITY_GRADE NUMBER NOT NULL,
    MIN_PLAYERS NUMBER(2) NOT NULL,
    MAX_PLAYERS NUMBER(3) NOT NULL,
    ROOM_DESC VARCHAR2(4000),
    ROOM_IMG VARCHAR2(200) NOT NULL,
    PRICE NUMBER(6) NOT NULL,
    IS_ADULT NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ROOM PRIMARY KEY (ROOM_ID),
    CONSTRAINT FK_ROOM_CAFE_ID FOREIGN KEY (CAFE_ID) REFERENCES CAFE(CAFE_ID),
    CONSTRAINT FK_ROOM_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES ROOM_GENRE(GENRE_ID),
    CONSTRAINT FK_ROOM_DIFF FOREIGN KEY (DIFFICULTY) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_ROOM_HORROR FOREIGN KEY (HORROR_GRADE) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_ROOM_ACTIV FOREIGN KEY (ACTIVITY_GRADE) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_ROOM_IS_ADULT FOREIGN KEY (IS_ADULT) REFERENCES COMMON(COMMON_ID),
    CONSTRAINT CK_ROOM_MIN_PLAYERS CHECK (MIN_PLAYERS >= 1),
    CONSTRAINT CK_ROOM_MAX_PLAYERS CHECK (MAX_PLAYERS >= MIN_PLAYERS)
);

--COMMENT ON COLUMN ROOM.DURATION IS '분단위';
--COMMENT ON COLUMN ROOM.ROOM_IMG IS '이미지경로';
--COMMENT ON COLUMN ROOM.PRICE IS '원단위, 1인기준가격';

-- 23. MANAGER_HISTORY
CREATE TABLE MANAGER_HISTORY (
    MANAGER_HISTORY_ID NUMBER,
    CAFE_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    REG_EVENT_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MANAGER_HISTORY PRIMARY KEY (MANAGER_HISTORY_ID),
    CONSTRAINT FK_MGR_HIST_CAFE_ID FOREIGN KEY (CAFE_ID) REFERENCES CAFE(CAFE_ID),
    CONSTRAINT FK_MGR_HIST_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT FK_MGR_HIST_EVENT_ID FOREIGN KEY (REG_EVENT_ID) REFERENCES REG_EVENT(REG_EVENT_ID)
);

-- 24. PARTY_DROP
CREATE TABLE PARTY_DROP (
    PARTY_DROP_ID NUMBER,
    PARTY_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY_DROP PRIMARY KEY (PARTY_DROP_ID),
    CONSTRAINT FK_PARTY_DROP_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    CONSTRAINT UK_PARTY_DROP_PARTY_ID UNIQUE (PARTY_ID)
);

-- 25. PARTY_APPLY
CREATE TABLE PARTY_APPLY (
    APPLY_ID NUMBER,
    PARTY_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    APPLY_MESSAGE VARCHAR2(4000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY_APPLY PRIMARY KEY (APPLY_ID),
    CONSTRAINT FK_PARTY_APPLY_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    CONSTRAINT FK_PARTY_APPLY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID)
);

-- 26. PARTY_MESSAGE
CREATE TABLE PARTY_MESSAGE (
    MESSAGE_ID NUMBER,
    PARTY_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY_MESSAGE PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_PARTY_MSG_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    CONSTRAINT FK_PARTY_MSG_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID)
);

-- 27. RESERVATION
CREATE TABLE RESERVATION (
    RESERVATION_ID NUMBER,
    PARTY_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RESERVATION PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT FK_RESERV_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID),
    CONSTRAINT UK_RESERV_PARTY_ID UNIQUE (PARTY_ID)
);

-- 28. RESERVATION_CANCEL
CREATE TABLE RESERVATION_CANCEL (
    CANCEL_ID NUMBER,
    RESERVATION_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CANCEL_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RESERVATION_CANCEL PRIMARY KEY (CANCEL_ID),
    CONSTRAINT FK_RES_CANCEL_RESERV_ID FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID),
    CONSTRAINT FK_RES_CANCEL_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_RES_CANCEL_RESERV_ID UNIQUE (RESERVATION_ID)
);
--COMMENT ON COLUMN RESERVATION_CANCEL.USER_ID IS '본인 or 카페관계자';

-- 29. ATTENDANCE
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER,
    RESERVATION_ID NUMBER NOT NULL,
    USER_ID NUMBER,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCE_ID),
    CONSTRAINT FK_ATTEND_RESERV_ID FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID),
    CONSTRAINT FK_ATTEND_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_ATTEND_RESERV_ID UNIQUE (RESERVATION_ID)
);
--COMMENT ON COLUMN ATTENDANCE.USER_ID IS '카페관계자번호';
--COMMENT ON COLUMN ATTENDANCE.CREATED_AT IS '완료 버튼 클릭 시점 = 출석/노쇼 확정';


-- 30. ROOM_DROP
CREATE TABLE ROOM_DROP (
    ROOM_DROP_ID NUMBER,
    ROOM_ID NUMBER NOT NULL,
    DROP_REASON_ID NUMBER NOT NULL,
    DROP_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ROOM_DROP PRIMARY KEY (ROOM_DROP_ID),
    CONSTRAINT FK_ROOM_DROP_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
    CONSTRAINT FK_ROOM_DROP_REASON_ID FOREIGN KEY (DROP_REASON_ID) REFERENCES ROOM_DROP_REASON(DROP_REASON_ID)
);

-- 31. RES_OPEN
CREATE TABLE RES_OPEN (
    RES_OPEN_ID NUMBER,
    ROOM_ID NUMBER NOT NULL,
    OPEN_AT DATE NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RES_OPEN PRIMARY KEY (RES_OPEN_ID),
    CONSTRAINT FK_RES_OPEN_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
    CONSTRAINT FK_RES_OPEN_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT UK_ROOM_OPEN_AT UNIQUE (ROOM_ID, OPEN_AT)
);
--COMMENT ON COLUMN RES_OPEN.OPEN_AT IS 'date + time combined';
--COMMENT ON COLUMN RES_OPEN.USER_ID IS 'owner or manager';

-- 32. MESSAGE_DELETE
CREATE TABLE MESSAGE_DELETE (
    DELETE_ID NUMBER,
    MESSAGE_ID NUMBER NOT NULL,
    DELETED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MESSAGE_DELETE PRIMARY KEY (DELETE_ID),
    CONSTRAINT FK_MSG_DEL_MESSAGE_ID FOREIGN KEY (MESSAGE_ID) REFERENCES PARTY_MESSAGE(MESSAGE_ID),
    CONSTRAINT UK_MSG_DEL_MESSAGE_ID UNIQUE (MESSAGE_ID)
);

-- 33. PARTY_MEMBER
CREATE TABLE PARTY_MEMBER (
    MEMBER_ID NUMBER,
    APPLY_ID NUMBER NOT NULL,
    READY_AT DATE,
    JOINED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_PARTY_MBR_APPLY_ID FOREIGN KEY (APPLY_ID) REFERENCES PARTY_APPLY(APPLY_ID)
);

-- 34. ATTENDANCE_DETAIL
CREATE TABLE ATTENDANCE_DETAIL (
    DETAIL_ID NUMBER,
    ATTENDANCE_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    ATTEND_STATUS_ID NUMBER NOT NULL,
    CONSTRAINT PK_ATTENDANCE_DETAIL PRIMARY KEY (DETAIL_ID),
    CONSTRAINT FK_ATT_DET_ATTEND_ID FOREIGN KEY (ATTENDANCE_ID) REFERENCES ATTENDANCE(ATTENDANCE_ID),
    CONSTRAINT FK_ATT_DET_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT FK_ATT_DET_STATUS_ID FOREIGN KEY (ATTEND_STATUS_ID) REFERENCES ATTEND_STATUS(STATUS_ID),
    CONSTRAINT UK_ATTEND_ID_USER_ID UNIQUE (ATTENDANCE_ID, USER_ID)
);
--COMMENT ON COLUMN ATTENDANCE_DETAIL.USER_ID IS '파티장과 파티원';

-- 35. RES_DROP
CREATE TABLE RES_DROP (
    RES_DROP_ID NUMBER,
    RES_OPEN_ID NUMBER NOT NULL,
    DROP_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RES_DROP PRIMARY KEY (RES_DROP_ID),
    CONSTRAINT FK_RES_DROP_OPEN_ID FOREIGN KEY (RES_OPEN_ID) REFERENCES RES_OPEN(RES_OPEN_ID)
);

-- 36. PARTY_ROOM
CREATE TABLE PARTY_ROOM (
    PARTY_ROOM_ID NUMBER,
    RES_OPEN_ID NUMBER NOT NULL,
    PARTY_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY_ROOM PRIMARY KEY (PARTY_ROOM_ID),
    CONSTRAINT FK_PARTY_RM_OPEN_ID FOREIGN KEY (RES_OPEN_ID) REFERENCES RES_OPEN(RES_OPEN_ID),
    CONSTRAINT FK_PARTY_RM_PARTY_ID FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID)
);

-- 37. PARTY_KICK
CREATE TABLE PARTY_KICK (
    PARTY_KICK_ID NUMBER,
    MEMBER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PARTY_KICK PRIMARY KEY (PARTY_KICK_ID),
    CONSTRAINT FK_PARTY_KICK_MBR_ID FOREIGN KEY (MEMBER_ID) REFERENCES PARTY_MEMBER(MEMBER_ID),
    CONSTRAINT UK_PARTY_KICK_MBR_ID UNIQUE (MEMBER_ID)
);

-- 38. RECORD
CREATE TABLE RECORD (
    RECORD_ID NUMBER,
    DETAIL_ID NUMBER NOT NULL,
    PLAYER_COUNT NUMBER,
    IS_ESCAPED NUMBER,
    PLAY_TIME NUMBER,
    HINT_COUNT NUMBER,
    RECORD_COMMENT VARCHAR2(4000),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RECORD PRIMARY KEY (RECORD_ID),
    CONSTRAINT FK_RECORD_DETAIL_ID FOREIGN KEY (DETAIL_ID) REFERENCES ATTENDANCE_DETAIL(DETAIL_ID),
    CONSTRAINT FK_RECORD_IS_ESCAPED FOREIGN KEY (IS_ESCAPED) REFERENCES COMMON(COMMON_ID)
);
--COMMENT ON COLUMN RECORD.PLAY_TIME IS '초단위, 분*60+초';

-- 39. REVIEW
CREATE TABLE REVIEW (
    REVIEW_ID NUMBER,
    DETAIL_ID NUMBER NOT NULL,
    DIFFICULTY NUMBER NOT NULL,
    HORROR NUMBER NOT NULL,
    ACTIVITY NUMBER NOT NULL,
    IMMERSION NUMBER NOT NULL,
    SATISFACTION NUMBER NOT NULL,
    REVIEW_COMMENT VARCHAR2(4000),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_DETAIL_ID FOREIGN KEY (DETAIL_ID) REFERENCES ATTENDANCE_DETAIL(DETAIL_ID),
    CONSTRAINT FK_REVIEW_DIFF FOREIGN KEY (DIFFICULTY) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_REVIEW_HORROR FOREIGN KEY (HORROR) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_REVIEW_ACTIV FOREIGN KEY (ACTIVITY) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_REVIEW_IMMERSION FOREIGN KEY (IMMERSION) REFERENCES GRADE(GRADE_ID),
    CONSTRAINT FK_REVIEW_SATISF FOREIGN KEY (SATISFACTION) REFERENCES GRADE(GRADE_ID)
);

-- 40. MUTUAL_EVALUATION
CREATE TABLE MUTUAL_EVALUATION (
    EVAL_ID NUMBER,
    DETAIL_ID NUMBER NOT NULL,
    TARGET_ID NUMBER NOT NULL,
    QUESTION_ID NUMBER NOT NULL,
    ANSWER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MUTUAL_EVALUATION PRIMARY KEY (EVAL_ID),
    CONSTRAINT FK_MUTUAL_EVAL_DET_ID FOREIGN KEY (DETAIL_ID) REFERENCES ATTENDANCE_DETAIL(DETAIL_ID),
    CONSTRAINT FK_MUTUAL_EVAL_TRGT_ID FOREIGN KEY (TARGET_ID) REFERENCES USER_ACCOUNT(USER_ID),
    CONSTRAINT FK_MUTUAL_EVAL_Q_ID FOREIGN KEY (QUESTION_ID) REFERENCES EVAL_QUESTION(QUESTION_ID),
    CONSTRAINT FK_MUTUAL_EVAL_A_ID FOREIGN KEY (ANSWER_ID) REFERENCES EVAL_ANSWER(ANSWER_ID),
    CONSTRAINT UK_MUTUAL_EVAL UNIQUE (DETAIL_ID, TARGET_ID, QUESTION_ID)
);



-- ===================================================================
-- ○ 테이블 일괄 삭제 (자식 테이블부터 역순으로 삭제)
-- ===================================================================
DROP TABLE MUTUAL_EVALUATION;
DROP TABLE REVIEW;
DROP TABLE RECORD;
DROP TABLE PARTY_KICK;
DROP TABLE PARTY_ROOM;
DROP TABLE RES_DROP;
DROP TABLE ATTENDANCE_DETAIL;
DROP TABLE PARTY_MEMBER;
DROP TABLE MESSAGE_DELETE;
DROP TABLE RES_OPEN;
DROP TABLE ROOM_DROP;
DROP TABLE ATTENDANCE;
DROP TABLE RESERVATION_CANCEL;
DROP TABLE RESERVATION;
DROP TABLE PARTY_MESSAGE;
DROP TABLE PARTY_APPLY;
DROP TABLE PARTY_DROP;
DROP TABLE MANAGER_HISTORY;
DROP TABLE ROOM;
DROP TABLE CAFE_DROP;
DROP TABLE PARTY;
DROP TABLE MANNER_HISTORY;
DROP TABLE CAFE;
DROP TABLE ADMIN_HISTORY;
DROP TABLE USER_DROP;
DROP TABLE USER_INFO;
DROP TABLE ATTEND_STATUS;
DROP TABLE EVAL_ANSWER;
DROP TABLE EVAL_QUESTION;
DROP TABLE GENDER_CONDITION;
DROP TABLE MANNER_REASON;
DROP TABLE ROOM_DROP_REASON;
DROP TABLE ROOM_GENRE;
DROP TABLE CAFE_DROP_REASON;
DROP TABLE ADMIN_INFO;
DROP TABLE ADMIN_ACCOUNT;
DROP TABLE USER_ACCOUNT;
DROP TABLE REG_EVENT;
DROP TABLE COMMON;
DROP TABLE GRADE; 



--
SELECT *
FROM TAB;
--
PURGE RECYCLEBIN;
--
--SELECT *
--FROM SEQ;

SELECT USER
FROM DUAL;

-- 제약 추가
-- =========================================================
-- 길이 제약 (LENGTH)
-- =========================================================
-- USER_ACCOUNT.LOGIN_ID : 6글자 이상 15글자 이하
ALTER TABLE USER_ACCOUNT
    ADD CONSTRAINT CK_USER_LOGIN_ID_LEN CHECK (LENGTH(LOGIN_ID) BETWEEN 6 AND 15);
--==>> Table USER_ACCOUNT이(가) 변경되었습니다.


-- USER_ACCOUNT.NICKNAME : 2글자 이상 10글자 이하
ALTER TABLE USER_ACCOUNT
    ADD CONSTRAINT CK_USER_NICKNAME_LEN CHECK (LENGTH(NICKNAME) BETWEEN 2 AND 10);
--==>> Table USER_ACCOUNT이(가) 변경되었습니다.


-- ADMIN_ACCOUNT.LOGIN_ID : 6글자 이상 15글자 이하
ALTER TABLE ADMIN_ACCOUNT
    ADD CONSTRAINT CK_ADMIN_LOGIN_ID_LEN CHECK (LENGTH(LOGIN_ID) BETWEEN 6 AND 15);
--==>> Table ADMIN_ACCOUNT이(가) 변경되었습니다.


-- =========================================================
-- 형식 제약 (하이픈 없이 = 숫자만)
-- =========================================================
-- ADMIN_INFO.PHONE : 하이픈 없이 11자리 숫자
ALTER TABLE ADMIN_INFO
    ADD CONSTRAINT CK_ADMIN_INFO_PHONE CHECK (REGEXP_LIKE(PHONE, '^[0-9]{11}$'));
--==>> Table ADMIN_INFO이(가) 변경되었습니다.

-- USER_INFO.PHONE : 하이픈 없이 11자리 숫자
ALTER TABLE USER_INFO
    ADD CONSTRAINT CK_USER_INFO_PHONE CHECK (REGEXP_LIKE(PHONE, '^[0-9]{11}$'));
--==>> Table USER_INFO이(가) 변경되었습니다.

-- USER_DROP.PHONE : 하이픈 없이 11자리 숫자
ALTER TABLE USER_DROP
    ADD CONSTRAINT CK_USER_DROP_PHONE CHECK (REGEXP_LIKE(PHONE, '^[0-9]{11}$'));
--==>> Table USER_DROP이(가) 변경되었습니다.


-- CAFE.BR_NO : 하이픈 제외 10자리 숫자 (사업자등록번호)
ALTER TABLE CAFE
    ADD CONSTRAINT CK_CAFE_BR_NO CHECK (REGEXP_LIKE(BR_NO, '^[0-9]{10}$'));
--==>> Table CAFE이(가) 변경되었습니다.

-- CAFE.PHONE : 하이픈 없이 숫자만 (지역번호 등 자릿수 가변)
ALTER TABLE CAFE
    ADD CONSTRAINT CK_CAFE_PHONE CHECK (REGEXP_LIKE(PHONE, '^[0-9]+$'));
--==>> Table CAFE이(가) 변경되었습니다.

-- =========================================================
-- 값 제약 (범례 값)
-- =========================================================
-- COMMON.COMMON_NAME : 'Y', 'N' 만 허용
ALTER TABLE COMMON
    ADD CONSTRAINT CK_COMMON_NAME CHECK (COMMON_NAME IN ('Y', 'N'));
--==>> Table COMMON이(가) 변경되었습니다.



-- 데이터 생성(범례) -------------------------------------------------------------------

-- 1. GRADE (1~5점)
INSERT INTO GRADE (GRADE_ID, GRADE_NAME) VALUES (GRADE_SEQ.NEXTVAL, '1점');
INSERT INTO GRADE (GRADE_ID, GRADE_NAME) VALUES (GRADE_SEQ.NEXTVAL, '2점');
INSERT INTO GRADE (GRADE_ID, GRADE_NAME) VALUES (GRADE_SEQ.NEXTVAL, '3점');
INSERT INTO GRADE (GRADE_ID, GRADE_NAME) VALUES (GRADE_SEQ.NEXTVAL, '4점');
INSERT INTO GRADE (GRADE_ID, GRADE_NAME) VALUES (GRADE_SEQ.NEXTVAL, '5점');
--==>>
/*

  GRADE_ID GRADE_NAME          
---------- --------------------
         1 1점                 
         2 2점                 
         3 3점                 
         4 4점                 
         5 5점         
*/

-- 2. COMMON (Y/N)
INSERT INTO COMMON (COMMON_ID, COMMON_NAME) VALUES (COMMON_SEQ.NEXTVAL, 'N');
INSERT INTO COMMON (COMMON_ID, COMMON_NAME) VALUES (COMMON_SEQ.NEXTVAL, 'Y');





SELECT *
FROM COMMON
ORDER BY COMMON_ID;
--==>>
/*
 COMMON_ID C
---------- -
         1 Y
         2 N
*/


-- 3. REG_EVENT (등록/해제)
INSERT INTO REG_EVENT (REG_EVENT_ID, REG_EVENT_NAME) VALUES (REG_EVENT_SEQ.NEXTVAL, '등록');
INSERT INTO REG_EVENT (REG_EVENT_ID, REG_EVENT_NAME) VALUES (REG_EVENT_SEQ.NEXTVAL, '해제');

SELECT *
FROM REG_EVENT
ORDER BY REG_EVENT_ID;

--==>>
/*
REG_EVENT_ID REG_EVENT_NAME      
------------ --------------------
           1 등록                
           2 해제   
*/



-- 7. CAFE_DROP_REASON
INSERT INTO CAFE_DROP_REASON (DROP_REASON_ID, DROP_REASON_NAME) VALUES (CAFE_DROP_REASON_SEQ.NEXTVAL, '폐업');
INSERT INTO CAFE_DROP_REASON (DROP_REASON_ID, DROP_REASON_NAME) VALUES (CAFE_DROP_REASON_SEQ.NEXTVAL, '개인사정');
INSERT INTO CAFE_DROP_REASON (DROP_REASON_ID, DROP_REASON_NAME) VALUES (CAFE_DROP_REASON_SEQ.NEXTVAL, '사용자신고');

SELECT *
FROM CAFE_DROP_REASON
ORDER BY DROP_REASON_ID;

--==>>
/*
DROP_REASON_ID DROP_REASON_NAME                                  
-------------- --------------------------------------------------
             1 폐업                                              
             2 개인사정                                           
             3 사용자신고    
*/



-- 8. ROOM_GENRE
INSERT INTO ROOM_GENRE (GENRE_ID, GENRE_NAME) VALUES (ROOM_GENRE_SEQ.NEXTVAL, '공포');
INSERT INTO ROOM_GENRE (GENRE_ID, GENRE_NAME) VALUES (ROOM_GENRE_SEQ.NEXTVAL, 'SF');
INSERT INTO ROOM_GENRE (GENRE_ID, GENRE_NAME) VALUES (ROOM_GENRE_SEQ.NEXTVAL, '스릴러');
INSERT INTO ROOM_GENRE (GENRE_ID, GENRE_NAME) VALUES (ROOM_GENRE_SEQ.NEXTVAL, '드라마');
INSERT INTO ROOM_GENRE (GENRE_ID, GENRE_NAME) VALUES (ROOM_GENRE_SEQ.NEXTVAL, '미스터리');
INSERT INTO ROOM_GENRE (GENRE_ID, GENRE_NAME) VALUES (ROOM_GENRE_SEQ.NEXTVAL, '감성');

SELECT *
FROM ROOM_GENRE
ORDER BY 1;
--==>>
/*
  GENRE_ID GENRE_NAME                                        
---------- --------------------------------------------------
         1 공포                                              
         2 SF                                                
         3 스릴러                                            
         4 드라마                                            
         5 미스터리                                           
         6 감성    
*/



-- 9. ROOM_DROP_REASON
INSERT INTO ROOM_DROP_REASON (DROP_REASON_ID, DROP_REASON_NAME) VALUES (ROOM_DROP_REASON_SEQ.NEXTVAL, '부적절한 내용');
INSERT INTO ROOM_DROP_REASON (DROP_REASON_ID, DROP_REASON_NAME) VALUES (ROOM_DROP_REASON_SEQ.NEXTVAL, '방 폐쇄');

SELECT *
FROM ROOM_DROP_REASON
ORDER BY 1;
--==>>
/*
DROP_REASON_ID DROP_REASON_NAME                                  
-------------- --------------------------------------------------
             1 부적절한 내용                                      
             2 방 폐쇄      
*/


-- 10. MANNER_REASON
INSERT INTO MANNER_REASON (REASON_ID, REASON_NAME) VALUES (MANNER_REASON_SEQ.NEXTVAL, '노쇼');
INSERT INTO MANNER_REASON (REASON_ID, REASON_NAME) VALUES (MANNER_REASON_SEQ.NEXTVAL, '상호평가');
INSERT INTO MANNER_REASON (REASON_ID, REASON_NAME) VALUES (MANNER_REASON_SEQ.NEXTVAL, '예약취소');

SELECT *
FROM MANNER_REASON
ORDER BY 1;
--==>>
/*
 REASON_ID REASON_NAME                                       
---------- --------------------------------------------------
         1 노쇼                                              
         2 상호평가                                           
         3 예약취소   
*/


-- 11. GENDER_CONDITION
INSERT INTO GENDER_CONDITION (GENDER_ID, GENDER_NAME) VALUES (GENDER_CONDITION_SEQ.NEXTVAL, '무관');
INSERT INTO GENDER_CONDITION (GENDER_ID, GENDER_NAME) VALUES (GENDER_CONDITION_SEQ.NEXTVAL, '동일성별');


SELECT *
FROM GENDER_CONDITION
ORDER BY 1;
--==>>
/*
 GENDER_ID GENDER_NAME                                       
---------- --------------------------------------------------
         1 동일성별                                           
         2 무관   
*/


-- 12. EVAL_QUESTION
INSERT INTO EVAL_QUESTION (QUESTION_ID, QUESTION) VALUES (EVAL_QUESTION_SEQ.NEXTVAL, '시간 약속을 잘 지켰나요?');
INSERT INTO EVAL_QUESTION (QUESTION_ID, QUESTION) VALUES (EVAL_QUESTION_SEQ.NEXTVAL, '함께 플레이하기 좋은 파티원이었나요?');


SELECT *
FROM EVAL_QUESTION
ORDER BY 1;
--==>>
/*
QUESTION_ID QUESTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
----------- ------------------------------------------
          1 시간 약속을 잘 지켰나요?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
          2 함께 플레이하기 좋은 파티원이었나요?    
*/

-- 13. EVAL_ANSWER
INSERT INTO EVAL_ANSWER (ANSWER_ID, ANSWER) VALUES (EVAL_ANSWER_SEQ.NEXTVAL, '좋음');
INSERT INTO EVAL_ANSWER (ANSWER_ID, ANSWER) VALUES (EVAL_ANSWER_SEQ.NEXTVAL, '나쁨');


SELECT *
FROM EVAL_ANSWER
ORDER BY 1;
--==>>
/*
 ANSWER_ID ANSWER                                            
---------- --------------------------------------------------
         1 좋음                                              
         2 나쁨    
*/

-- 14. ATTEND_STATUS
INSERT INTO ATTEND_STATUS (STATUS_ID, STATUS_NAME) VALUES (ATTEND_STATUS_SEQ.NEXTVAL, '출석');
INSERT INTO ATTEND_STATUS (STATUS_ID, STATUS_NAME) VALUES (ATTEND_STATUS_SEQ.NEXTVAL, '노쇼');


SELECT *
FROM ATTEND_STATUS
ORDER BY 1;
--==>>
/*
 STATUS_ID STATUS_NAME                                       
---------- --------------------------------------------------
         1 출석                                              
         2 노쇼                                              

*/


COMMIT;
--==>> 커밋 완료.





