SELECT USER
FROM DUAL;



-- 예약 중/예약취소/플레이완료인 목록 가져오기
SELECT RESERVATION_ID, CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, TOTAL_MEMBER
    , PARTY_ID, PARTY_NAME
    , PARTY_ROLE, RES_STATUS, RES_OPEN_ID
    , OPEN_AT, BOOKED_AT
    , ATTEND_STATUS, CANCEL_TYPE, CANCELED_AT
FROM (
    SELECT VRA.RESERVATION_ID, VRA.CAFE_ID, VRA.CAFE_NAME, VRA.ROOM_ID, VRA.ROOM_NAME, VRA.TOTAL_MEMBER
    , VRA.PARTY_ID, VRA.PARTY_NAME
    , CASE WHEN VRA.LEADER_ID = 5  -- 로그인 한 사용자 아이디 
            THEN '파티장' ELSE '파티원' 
          END AS PARTY_ROLE
    , CASE 
        WHEN VRA.CANCEL_AT IS NOT NULL THEN '예약 취소' 
        WHEN VRA.OPEN_AT < SYSDATE THEN  '플레이 완료'
        ELSE '예약 중' 
      END AS RES_STATUS
    , VRA.RES_OPEN_ID, VRA.OPEN_AT, VRA.BOOKED_AT
    , FN_GET_ATTEND_STATUS(VRA.RESERVATION_ID, 5) AS ATTEND_STATUS
    , CASE
        WHEN VRA.CANCEL_AT IS NULL THEN NULL
        WHEN FN_GET_USER_ROLE(VRA.RES_OPEN_ID, VRA.CANCEL_USER, VRA.CANCEL_AT) = 'USER' 
            THEN '취소 완료'
        WHEN FN_GET_USER_ROLE(VRA.RES_OPEN_ID, VRA.CANCEL_USER, VRA.CANCEL_AT) IN ('OWNER', 'MANAGER')
            THEN '매장 취소'       
        ELSE '알 수 없음' 
            END AS CANCEL_TYPE
    , VRA.CANCEL_AT AS CANCELED_AT
    FROM VW_RESERVATION_ALL VRA
       -- LEFT JOIN RESERVATION_CANCEL RC
      --  ON VRA.RESERVATION_ID = RC.RESERVATION_ID
    WHERE VRA.LEADER_ID = 5 --로그인 한 사용자아이디
        OR VRA.PARTY_ID IN (
            SELECT PA.PARTY_ID
            FROM PARTY_MEMBER PM 
                JOIN PARTY_APPLY PA
                ON PM.APPLY_ID = PA.APPLY_ID
            WHERE PA.USER_ID = 5 -- 로그인 한 사용자 아이디
                AND NOT EXISTS(
                                SELECT PK.MEMBER_ID
                                FROM PARTY_KICK PK
                                WHERE PK.MEMBER_ID = PM.MEMBER_ID
                                )
        )
)
-- 분기 시 사용 
WHERE RES_STATUS = '플레이 완료'
ORDER BY OPEN_AT DESC
		OFFSET 0 ROWS
		FETCH FIRST 10 ROWS ONLY;
        
WHERE RES_STATUS = '예약 중'
WHERE RES_STATUS = '예약 취소'




ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT *
FROM VW_RESERVATION_ALL;


SELECT * FROM VW_RESERVATION_ALL WHERE ROWNUM <= 5;



-- 예약 취소에 따른 파티원들과 파티장의 이름, 닉네임, 메일 목록 쿼리 구성

SELECT P.USER_ID AS LEADER_ID
, 
FROM RESERVATION RV
    JOIN PARTY P
        ON RV.PARTY_ID = P.PARTY_ID
    JOIN 




SELECT *
FROM PARTY_MEMBER PM
WHERE NOT EXISTS (
    SELECT 1 
    FROM PARTY_KICK PK 
    WHERE PM.MEMBER_ID = PK.MEMBER_ID
);

SELECT *
FROM PARTY_APPLY
WHERE PARTY_ID = 2;

SELECT *
FROM PARTY_MEMBER;

SELECT PARTY_ID
FROM VW_RES_OPEN_CANCELED
WHERE RESERVATION_ID = 3 
;

SELECT *
FROM PARTY_APPLY PA
    JOIN PARTY_MEMBER PM
        ON PA.APPLY_ID = PM.APPLY_ID
WHERE PARTY_ID =1;

select *
from party_drop;

-- 어떤 파티에 어떤 파티원이 있는지 조회

-- reservation_id로 파티 아이디 조회
-- party_drop 테이블에서 party_id와 비교해서 같은거 찾아 확인(취소된거 맞는지)
-- party_id로 파티장과 파티원 user_id 목록을 가져와서
-- User_info에서 찾기

-- 파티원 조회
SELECT PD.PARTY_ID, VRA.PARTY_NAME
, VRA.CAFE_ID, VRA.CAFE_NAME
, VRA.ROOM_ID, VRA.ROOM_NAME
, VRA.RES_OPEN_ID
, TO_CHAR(VRA.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
, PA.USER_ID, UA.NICKNAME, UI.NAME, UI.EMAIL
FROM PARTY_DROP PD
    JOIN PARTY_APPLY PA
        ON PD.PARTY_ID = PA.PARTY_ID
    JOIN PARTY_MEMBER PM
        ON PA.APPLY_ID = PM.APPLY_ID
    JOIN USER_ACCOUNT UA 
        ON PA.USER_ID = UA.USER_ID
    JOIN USER_INFO UI
        ON UA.USER_ID = UI.USER_ID
    JOIN (
            SELECT PARTY_ID, PARTY_NAME, CAFE_ID, CAFE_NAME
                 , ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
            FROM VW_RESERVATION_ALL
            WHERE RESERVATION_ID = 3
        ) VRA ON VRA.PARTY_ID = PD.PARTY_ID
WHERE PD.PARTY_ID = (
        SELECT PARTY_ID FROM RESERVATION
        WHERE RESERVATION_ID = 3
    ) AND PM.MEMBER_ID NOT IN( SELECT MEMBER_ID
                              FROM PARTY_KICK      
    )
UNION
-- 파티장 조회
SELECT PD.PARTY_ID, VRA.PARTY_NAME
, VRA.CAFE_ID, VRA.CAFE_NAME
, VRA.ROOM_ID, VRA.ROOM_NAME
, VRA.RES_OPEN_ID
, TO_CHAR(VRA.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
, P.USER_ID, UA.NICKNAME, UI.NAME, UI.EMAIL
FROM PARTY_DROP PD
    JOIN PARTY P
        ON PD.PARTY_ID = P.PARTY_ID
    JOIN USER_ACCOUNT UA
        ON P.USER_ID = UA.USER_ID
    JOIN USER_INFO UI
        ON UA.USER_ID = UI.USER_ID
    JOIN (
            SELECT PARTY_ID, PARTY_NAME, CAFE_ID, CAFE_NAME
                 , ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
            FROM VW_RESERVATION_ALL
            WHERE RESERVATION_ID = 3
        ) VRA ON VRA.PARTY_ID = PD.PARTY_ID
WHERE PD.PARTY_ID = (
        SELECT PARTY_ID FROM RESERVATION
        WHERE RESERVATION_ID = 3
    );





-- 카페 목록 조회
SELECT DISTINCT CAFE_ID, CAFE_NAME
FROM VW_CAFE_ROOM_INFO
WHERE CAFE_OWNER = 15 OR CAFE_MANAGER= 15
;


-- 뷰에서 15번 유저 데이터 있는지 확인
SELECT DISTINCT CAFE_ID, CAFE_NAME, CAFE_OWNER, CAFE_MANAGER
FROM VW_CAFE_ROOM_INFO
WHERE CAFE_OWNER = 15 OR CAFE_MANAGER = 15;

-- 테마 목록 조회
SELECT ROOM_ID, ROOM_NAME
FROM ROOM
WHERE CAFE_ID =1
AND ROOM_ID NOT IN (SELECT ROOM_ID FROM ROOM_DROP)
ORDER BY ROOM_NAME
;

select *
from user_account;


-- 등록된 예약 오픈 목록 조회
SELECT RO.RES_OPEN_ID
, R.CAFE_ID, C.CAFE_NAME
, RO.ROOM_ID, R.ROOM_NAME
, TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
FROM RES_OPEN RO
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
    JOIN CAFE C
    ON R.CAFE_ID = C.CAFE_ID
WHERE R.CAFE_ID IN(
    SELECT DISTINCT CAFE_ID
    FROM VW_CAFE_ROOM_INFO
    WHERE CAFE_OWNER = 15 OR CAFE_MANAGER= 15 
) 
AND RO.RES_OPEN_ID NOT IN (SELECT RES_OPEN_ID FROM RES_DROP)
--AND TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') = '2026-07-19'
--AND R.CAFE_ID = 1
ORDER BY CAFE_ID ASC, ROOM_ID ASC, OPEN_AT DESC
;

SELECT *
FROM RES_DROP;

SELECT RO.RES_OPEN_ID, R.CAFE_ID, R.ROOM_ID
, TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') AS OPEN_AT
FROM RES_OPEN RO
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
WHERE RO.RES_OPEN_ID NOT IN 
    (SELECT RES_OPEN_ID FROM RES_DROP)
AND R.CAFE_ID = 1
--AND TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') = '2026-07-19' 
ORDER BY CAFE_ID ASC, ROOM_ID ASC, OPEN_AT DESC;


-- 예약 오픈 등록 데이터 개수 
SELECT COUNT(*)
FROM RES_OPEN RO
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
WHERE RO.RES_OPEN_ID NOT IN 
    (SELECT RES_OPEN_ID FROM RES_DROP)
AND R.CAFE_ID IN (
                    SELECT DISTINCT CAFE_ID
                    FROM VW_CAFE_ROOM_INFO
                    WHERE CAFE_OWNER = 15 OR CAFE_MANAGER = 15
                 )   
AND R.CAFE_ID = 1
AND TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') = '2026-07-19' ;



-- 카페운영자 
-- 카페의 예약 현황 목록

-- 예약번호, 카페명, 테마명, 예약일, 예약자명, 예약자 연락처, 예약 인원 수
SELECT CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
, RESERVATION_ID
, LEADER_ID AS BOOKER_ID, LEADER_NAME AS BOOKER_NAME, LEADER_PHONE AS BOOKER_TEL
, TOTAL_MEMBER
FROM VW_RES_OPEN_BOOKED
WHERE CAFE_ID = 4
ORDER BY OPEN_AT
;

-- 카페 예약 목록 조회
-- 룸아이디로 조회
SELECT CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
, RESERVATION_ID
FROM VW_RES_OPEN_BOOKED
WHERE 
TO_CHAR(OPEN_AT,'YYYY-MM-DD') = '2026-03-22' 
AND CAFE_ID = 2
AND ROOM_ID = 3
ORDER BY OPEN_AT
;

-- 카페 예약 상세 조회
SELECT RESERVATION_ID, CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME
, OPEN_AT
FROM VW_RES_OPEN_BOOKED
WHERE CAFE_ID = 1;


SELECT *
FROM VW_RES_OPEN_BOOKED;

SELECT FN_GET_RESERVATION_ROLE()
FROM DUAL;


-- 유저아이디로 관리가능한 카페 목록 조회
SELECT CAFE_ID
FROM CAFE 
WHERE USER_ID=8;

SELECT *
FROM MANAGER_HISTORY
ORDER BY CAFE_ID ASC, USER_ID ASC, CREATED_AT DESC;



-- 카페ID + 유저ID 기준으로 가장 최근 이벤트가 1(등록)인지 확인
SELECT USER_ID, CAFE_ID, REG_EVENT_ID
FROM (
    SELECT USER_ID, CAFE_ID, REG_EVENT_ID,
           ROW_NUMBER() OVER (
               PARTITION BY CAFE_ID, USER_ID 
               ORDER BY CREATED_AT DESC
           ) AS RN
    FROM MANAGER_HISTORY
)
WHERE RN = 1
  AND REG_EVENT_ID = 1  -- 가장 최근 이벤트가 등록



-- 카페아이디랑 유저아이디를 받아올거임, 룸아이디일수도?
-- 카페아이디이거나 룸아이디
SELECT CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, 
       RES_OPEN_ID, OPEN_AT, RESERVATION_ID
FROM VW_RES_OPEN_BOOKED
WHERE CAFE_ID IN (
    -- 사장인 카페
    SELECT CAFE_ID FROM CAFE
    WHERE USER_ID = #{loginId}
    
    UNION
    
    -- 현재 활성 매니저인 카페
    SELECT CAFE_ID
    FROM (
        SELECT CAFE_ID, REG_EVENT_ID,
               ROW_NUMBER() OVER (
                   PARTITION BY CAFE_ID, USER_ID
                   ORDER BY CREATED_AT DESC
               ) AS RN
        FROM MANAGER_HISTORY
        WHERE USER_ID = #{loginId}
    )
    WHERE RN = 1
      AND REG_EVENT_ID = 1
)
AND (#{cafeId} IS NULL OR CAFE_ID = #{cafeId})
AND (#{roomId} IS NULL OR ROOM_ID = #{roomId})
AND (#{date} IS NULL OR TO_CHAR(OPEN_AT, 'YYYY-MM-DD') = #{date})
ORDER BY OPEN_AT

-- 더보기 방식으로 구현 시도(예약 목록 조회)
SELECT * FROM (
        SELECT ROWNUM AS RN, A.*
        FROM (
            SELECT CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME,
                   RES_OPEN_ID, OPEN_AT, RESERVATION_ID
            FROM VW_RES_OPEN_BOOKED
            WHERE CAFE_ID IN (
                SELECT CAFE_ID FROM CAFE
                WHERE USER_ID = #{userId}
                UNION
                SELECT CAFE_ID
                FROM (
                    SELECT CAFE_ID, REG_EVENT_ID,
                           ROW_NUMBER() OVER (
                               PARTITION BY CAFE_ID, USER_ID
                               ORDER BY CREATED_AT DESC
                           ) AS RN
                    FROM MANAGER_HISTORY
                    WHERE USER_ID = #{userId}
                )
                WHERE RN = 1
                  AND REG_EVENT_ID = 1
            )
            AND TO_CHAR(OPEN_AT, 'YYYY-MM-DD') = #{openAt}
            AND CAFE_ID = #{cafeId}
            <if test="roomId != null">
                AND ROOM_ID = #{roomId}
            </if>
            ORDER BY ROOM_NAME, OPEN_AT
        ) A
    )
    WHERE RN BETWEEN #{offset} + 1 AND #{offset} + #{limit}





SELECT *
FROM PARTY;
파티장 1 신청자 12

SELECT *
FROM PARTY_ROOM;

ROOM_ID 27
RES_OPEN_ID 57

INSERT INTO PARTY_ROOM
VALUES (PARTY_ROOM_SEQ.NEXTVAL, 57,21, SYSDATE);

SELECT *
FROM RES_OPEN
ORDER BY CREATED_AT DESC;

SELECT *
FROM ROOM
ORDER BY CREATED_AT DESC;

APPLY_ID 49
PARTY_ID 21
USER_ID 12
APPLY_MESSAGE
CREATED_AT


INSERT INTO PARTY_APPLY
VALUES(PARTY_APPLY_SEQ.NEXTVAL, 21, 15, '신청!',SYSDATE);

SELECT *
FROM PARTY_APPLY;

INSERT INTO PARTY_MEMBER
VALUES(PARTY_MEMBER_SEQ.NEXTVAL, 49, SYSDATE, SYSDATE);

SELECT *
FROM PARTY_MEMBER;

MEMBER_ID 48

SELECT *
FROM PARTY_MEMBER
WHERE APPLY_ID = 48;

INSERT INTO RESERVATION
VALUES(RESERVATION_SEQ.NEXTVAL, 21, SYSDATE);

SELECT *
FROM RESERVATION
ORDER BY CREATED_AT DESC;

RESERVATION_ID 16 

SELECT *
FROM RES_OPEN
WHERE RES_OPEN_ID=46;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT *
FROM CAFE
WHERE CAFE_ID = 4;




CASE 
    WHEN LENGTH(LEADER_PHONE) = 11 
        THEN SUBSTR(LEADER_PHONE,1,3)||'-'||SUBSTR(LEADER_PHONE,4,4)||'-'||SUBSTR(LEADER_PHONE,8,4)
    ELSE LEADER_PHONE
    END AS BOOKER_TEL

SELECT *
FROM USER_ACCOUNT;
select *
from cafe;


--userId
8,1,15 제외

-- 파티장
2(user0009)
-- 파티원
5(user0017)
6(user0010)
10(user0004)



SELECT *
FROM PARTY
ORDER BY CREATED_AT DESC;


SELECT *
FROM VW_ACTIVE_RES_OPEN
ORDER BY CREATED_AT DESC;

SELECT *
FROM PARTY_ROOM
ORDER BY CREATED_AT DESC;

SELECT *
FROM PARTY_APPLY
ORDER BY CREATED_AT DESC;

SELECT *
FROM PARTY_MEMBER
ORDER BY JOINED_AT DESC;

SELECT *
FROM RESERVATION
ORDER BY CREATED_AT DESC;

INSERT INTO PARTY_ROOM(PARTY_ROOM_ID, RES_OPEN_ID, PARTY_ID, CREATED_AT)
VALUES (PARTY_ROOM_SEQ.NEXTVAL, 87,22, SYSDATE);

INSERT INTO PARTY_APPLY(APPLY_ID, PARTY_ID, USER_ID, APPLY_MESSAGE, CREATED_AT)
VALUES(PARTY_APPLY_SEQ.NEXTVAL, 22, 5, '신청!',SYSDATE);

INSERT INTO PARTY_MEMBER(MEMBER_ID, APPLY_ID, READY_AT, JOINED_AT)
VALUES(PARTY_MEMBER_SEQ.NEXTVAL, 51, SYSDATE, SYSDATE);

INSERT INTO RESERVATION(RESERVATION_ID, PARTY_ID, CREATED_AT)
VALUES(RESERVATION_SEQ.NEXTVAL, 22, SYSDATE);


COMMIT;








-- 예약 정보 확인
-- party_id, user_id

-- cafeid, cafenaem, room_id, room_name, open_at,
-- leader_id, leader_name, leader_tel, total_member
-- room_img, room_price
SELECT p.party_id, C.CAFE_ID, C.CAFE_NAME
, R.ROOM_ID, R.ROOM_NAME
, RO.OPEN_AT
, P.USER_ID AS BOOKER_ID
, UI.NAME AS BOOKER_NAME
, UI.PHONE AS BOOKER_TEL
, R.ROOM_IMG, R.PRICE
, FN_MEMBER_COUNT(16) AS TOTAL_MEMBER
FROM PARTY P 
    JOIN PARTY_ROOM PR
    ON P.PARTY_ID = PR.PARTY_ID
    JOIN RES_OPEN RO
    ON PR.RES_OPEN_ID = RO.RES_OPEN_ID
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
    JOIN CAFE C
    ON R.CAFE_ID = C.CAFE_ID
    JOIN USER_INFO UI
    ON C.USER_ID = UI.USER_ID
WHERE P.PARTY_ID = 16
AND P.USER_ID = 20
;



SELECT ROOM_ID, ROOM_IMG
FROM ROOM
WHERE ROOM_IMG LIKE '/images/%';

UPDATE ROOM
SET ROOM_IMG='room_12.jpg'
WHERE ROOM_ID = 12;

commit;







-- 메인페이지
-- 인기테마 4개(리뷰평균 높은 순, 동점이라면 최근 개설된 순으로 정렬)
SELECT *
FROM (
    SELECT 
        C.CAFE_NAME,
        R.ROOM_ID, 
        R.ROOM_NAME, 
        RG.GENRE_NAME,
        R.ROOM_IMG, 
        R.IS_ADULT, 
        R.CREATED_AT,
        (
            SELECT AVG(RV.SATISFACTION)
            FROM REVIEW RV
                JOIN ATTENDANCE_DETAIL AD ON RV.DETAIL_ID = AD.DETAIL_ID
                JOIN ATTENDANCE AT ON AD.ATTENDANCE_ID = AT.ATTENDANCE_ID
                JOIN RESERVATION RES ON AT.RESERVATION_ID = RES.RESERVATION_ID
                JOIN PARTY P ON RES.PARTY_ID = P.PARTY_ID
                JOIN PARTY_ROOM PR ON PR.PARTY_ID = P.PARTY_ID
                JOIN RES_OPEN RO ON PR.RES_OPEN_ID = RO.RES_OPEN_ID
            WHERE RO.ROOM_ID = R.ROOM_ID
        ) AS AVG_GRADE
    FROM ROOM R
    JOIN ROOM_GENRE RG 
        ON R.GENRE_ID = RG.GENRE_ID
    JOIN CAFE C 
        ON R.CAFE_ID = C.CAFE_ID
)
ORDER BY AVG_GRADE DESC NULLS LAST, CREATED_AT DESC
FETCH FIRST 4 ROWS ONLY
;

-- 최근개설 모집

SELECT VAP.PARTY_ID, VAP.PARTY_NAME
, C.CAFE_NAME, R.ROOM_NAME
, TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
, (
    SELECT ROUND(AVG(TEMP),1)
    FROM VW_PARTY_ACTIVE_MEMBER
    WHERE PARTY_ID = VAP.PARTY_ID
) AS AVG_TEMP
, FN_MEMBER_COUNT(VAP.PARTY_ID) AS PARTY_CNT
, R.MAX_PLAYERS
FROM VW_ACTIVE_PARTY VAP
    JOIN RES_OPEN RO
    ON RO.RES_OPEN_ID = VAP.RES_OPEN_ID
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
    JOIN CAFE C
    ON R.CAFE_ID = C.CAFE_ID
ORDER BY VAP.CREATED_AT DESC
FETCH FIRST 3 ROWS ONLY
;

select *
from res_open
where res_open_id = 99
order by 1 desc;

update res_open
set open_at = to_date('2026-06-14 20:30','YYYY-MM-DD HH24:MI')
WHERE RES_OPEN_ID = 99;

COMMIT;

select *
from VW_RES_OPEN_BOOKED;


select *
from party
order by 1 desc;


select *
from vw_cafe_room_info;

select *
from user_account
where user_id = 4;

select *
from reservation_cancel;

select *
from VW_CAFE_ROOM_INFO;

