SELECT USER
FROM DUAL;



-- 로그인한 유저의 예약 목록 뽑아오기 
-- 사용자예약아이디, 카페아이디, 카페명, 테마아이디, 테마명, 예약인원, 파티장/파티장, 예약상태(예약중/플레이완료/예약취소)
-- 예약오픈아이디, 예약오픈일시, 예약한날짜, 출석여부(출석완료/노쇼/출석미등록), 취소타입(취소완료/매장취소), 취소 일자
/*
SELECT VRA.RESERVATION_ID, VRA.CAFE_ID, VRA.CAFE_NAME, VRA.ROOM_ID, VRA.ROOM_NAME, VRA.TOTAL_MEMBER
, CASE WHEN VRA.LEADER_ID = :USER_ID  -- 로그인 한 사용자 아이디 
        THEN '파티장' ELSE '파티원' 
      END AS PARTY_ROLE
, CASE 
    WHEN RC.RESERVATION_ID IS NOT NULL THEN '예약 취소' 
    WHEN VRA.OPEN_AT < SYSDATE THEN  '플레이 완료'
    ELSE '예약 중' 
  END AS RES_STATUS
, VRA.RES_OPEN_ID, VRA.OPEN_AT, VRA.BOOKED_AT
, FN_GET_ATTEND_STATUS(VRA.RESERVATION_ID, :USER_ID) AS ATTEND_STATUS
, CASE
    WHEN RC.RESERVATION_ID IS NULL THEN NULL
    WHEN FN_GET_USER_ROLE(VRA.RES_OPEN_ID, RC.USER_ID, RC.CANCEL_AT) = 'USER' 
        THEN '취소 완료'
    WHEN FN_GET_USER_ROLE(VRA.RES_OPEN_ID, RC.USER_ID, RC.CANCEL_AT) IN ('OWNER', 'MANAGER')
        THEN '매장 취소'       
    ELSE '알 수 없음' 
        END AS CANCEL_TYPE
, RC.CANCEL_AT AS CANCELED_AT
FROM VW_RESERVATION_ALL VRA
    LEFT JOIN RESERVATION_CANCEL RC
    ON VRA.RESERVATION_ID = RC.RESERVATION_ID
WHERE VRA.LEADER_ID = :USER_ID --로그인 한 사용자아이디
    OR VRA.PARTY_ID IN (
        SELECT PA.PARTY_ID
        FROM PARTY_MEMBER PM 
            JOIN PARTY_APPLY PA
            ON PM.APPLY_ID = PA.APPLY_ID
        WHERE PA.USER_ID = :USER_ID -- 로그인 한 사용자 아이디
            AND NOT EXISTS(
                            SELECT PK.MEMBER_ID
                            FROM PARTY_KICK PK
                            WHERE PK.MEMBER_ID = PM.MEMBER_ID
                            )
    );


*/



-- 예약 중/예약취소/플레이완료인 목록 가져오기
SELECT RESERVATION_ID, CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, TOTAL_MEMBER
    , PARTY_ID, PARTY_NAME
    , PARTY_ROLE, RES_STATUS, RES_OPEN_ID
    , OPEN_AT, BOOKED_AT
    , ATTEND_STATUS, CANCEL_TYPE, CANCELED_AT
FROM (
    SELECT VRA.RESERVATION_ID, VRA.CAFE_ID, VRA.CAFE_NAME, VRA.ROOM_ID, VRA.ROOM_NAME, VRA.TOTAL_MEMBER
    , VRA.PARTY_ID, VRA.PARTY_NAME
    , CASE WHEN VRA.LEADER_ID = 5  -- 로그인 한 사용자 아이디 
            THEN '파티장' ELSE '파티원' 
          END AS PARTY_ROLE
    , CASE 
        WHEN VRA.CANCEL_AT IS NOT NULL THEN '예약 취소' 
        WHEN VRA.OPEN_AT < SYSDATE THEN  '플레이 완료'
        ELSE '예약 중' 
      END AS RES_STATUS
    , VRA.RES_OPEN_ID, VRA.OPEN_AT, VRA.BOOKED_AT
    , FN_GET_ATTEND_STATUS(VRA.RESERVATION_ID, 5) AS ATTEND_STATUS
    , CASE
        WHEN VRA.CANCEL_AT IS NULL THEN NULL
        WHEN FN_GET_USER_ROLE(VRA.RES_OPEN_ID, VRA.CANCEL_USER, VRA.CANCEL_AT) = 'USER' 
            THEN '취소 완료'
        WHEN FN_GET_USER_ROLE(VRA.RES_OPEN_ID, VRA.CANCEL_USER, VRA.CANCEL_AT) IN ('OWNER', 'MANAGER')
            THEN '매장 취소'       
        ELSE '알 수 없음' 
            END AS CANCEL_TYPE
    , VRA.CANCEL_AT AS CANCELED_AT
    FROM VW_RESERVATION_ALL VRA
       -- LEFT JOIN RESERVATION_CANCEL RC
      --  ON VRA.RESERVATION_ID = RC.RESERVATION_ID
    WHERE VRA.LEADER_ID = 5 --로그인 한 사용자아이디
        OR VRA.PARTY_ID IN (
            SELECT PA.PARTY_ID
            FROM PARTY_MEMBER PM 
                JOIN PARTY_APPLY PA
                ON PM.APPLY_ID = PA.APPLY_ID
            WHERE PA.USER_ID = 5 -- 로그인 한 사용자 아이디
                AND NOT EXISTS(
                                SELECT PK.MEMBER_ID
                                FROM PARTY_KICK PK
                                WHERE PK.MEMBER_ID = PM.MEMBER_ID
                                )
        )
)
-- 분기 시 사용 
WHERE RES_STATUS = '플레이 완료'
ORDER BY OPEN_AT DESC
		OFFSET 0 ROWS
		FETCH FIRST 10 ROWS ONLY;
        
WHERE RES_STATUS = '예약 중'
WHERE RES_STATUS = '예약 취소'




ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT *
FROM VW_RESERVATION_ALL;


SELECT * FROM VW_RESERVATION_ALL WHERE ROWNUM <= 5;



-- 예약 취소에 따른 파티원들과 파티장의 이름, 닉네임, 메일 목록 쿼리 구성

SELECT P.USER_ID AS LEADER_ID
, 
FROM RESERVATION RV
    JOIN PARTY P
        ON RV.PARTY_ID = P.PARTY_ID
    JOIN 




SELECT *
FROM PARTY_MEMBER PM
WHERE NOT EXISTS (
    SELECT 1 
    FROM PARTY_KICK PK 
    WHERE PM.MEMBER_ID = PK.MEMBER_ID
);

SELECT *
FROM PARTY_APPLY
WHERE PARTY_ID = 2;

SELECT *
FROM PARTY_MEMBER;

SELECT PARTY_ID
FROM VW_RES_OPEN_CANCELED
WHERE RESERVATION_ID = 3 
;

SELECT *
FROM PARTY_APPLY PA
    JOIN PARTY_MEMBER PM
        ON PA.APPLY_ID = PM.APPLY_ID
WHERE PARTY_ID =1;

select *
from party_drop;

-- 어떤 파티에 어떤 파티원이 있는지 조회

-- reservation_id로 파티 아이디 조회
-- party_drop 테이블에서 party_id와 비교해서 같은거 찾아 확인(취소된거 맞는지)
-- party_id로 파티장과 파티원 user_id 목록을 가져와서
-- User_info에서 찾기

-- 파티원 조회
SELECT PD.PARTY_ID, VRA.PARTY_NAME
, VRA.CAFE_ID, VRA.CAFE_NAME
, VRA.ROOM_ID, VRA.ROOM_NAME
, VRA.RES_OPEN_ID
, TO_CHAR(VRA.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
, PA.USER_ID, UA.NICKNAME, UI.NAME, UI.EMAIL
FROM PARTY_DROP PD
    JOIN PARTY_APPLY PA
        ON PD.PARTY_ID = PA.PARTY_ID
    JOIN PARTY_MEMBER PM
        ON PA.APPLY_ID = PM.APPLY_ID
    JOIN USER_ACCOUNT UA 
        ON PA.USER_ID = UA.USER_ID
    JOIN USER_INFO UI
        ON UA.USER_ID = UI.USER_ID
    JOIN (
            SELECT PARTY_ID, PARTY_NAME, CAFE_ID, CAFE_NAME
                 , ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
            FROM VW_RESERVATION_ALL
            WHERE RESERVATION_ID = 3
        ) VRA ON VRA.PARTY_ID = PD.PARTY_ID
WHERE PD.PARTY_ID = (
        SELECT PARTY_ID FROM RESERVATION
        WHERE RESERVATION_ID = 3
    ) AND PM.MEMBER_ID NOT IN( SELECT MEMBER_ID
                              FROM PARTY_KICK      
    )
UNION
-- 파티장 조회
SELECT PD.PARTY_ID, VRA.PARTY_NAME
, VRA.CAFE_ID, VRA.CAFE_NAME
, VRA.ROOM_ID, VRA.ROOM_NAME
, VRA.RES_OPEN_ID
, TO_CHAR(VRA.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
, P.USER_ID, UA.NICKNAME, UI.NAME, UI.EMAIL
FROM PARTY_DROP PD
    JOIN PARTY P
        ON PD.PARTY_ID = P.PARTY_ID
    JOIN USER_ACCOUNT UA
        ON P.USER_ID = UA.USER_ID
    JOIN USER_INFO UI
        ON UA.USER_ID = UI.USER_ID
    JOIN (
            SELECT PARTY_ID, PARTY_NAME, CAFE_ID, CAFE_NAME
                 , ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
            FROM VW_RESERVATION_ALL
            WHERE RESERVATION_ID = 3
        ) VRA ON VRA.PARTY_ID = PD.PARTY_ID
WHERE PD.PARTY_ID = (
        SELECT PARTY_ID FROM RESERVATION
        WHERE RESERVATION_ID = 3
    );





-- 카페 목록 조회
SELECT DISTINCT CAFE_ID, CAFE_NAME
FROM VW_CAFE_ROOM_INFO
WHERE CAFE_OWNER = 15 OR CAFE_MANAGER= 15
;


-- 뷰에서 15번 유저 데이터 있는지 확인
SELECT DISTINCT CAFE_ID, CAFE_NAME, CAFE_OWNER, CAFE_MANAGER
FROM VW_CAFE_ROOM_INFO
WHERE CAFE_OWNER = 15 OR CAFE_MANAGER = 15;

-- 테마 목록 조회
SELECT ROOM_ID, ROOM_NAME
FROM ROOM
WHERE CAFE_ID =1
AND ROOM_ID NOT IN (SELECT ROOM_ID FROM ROOM_DROP)
ORDER BY ROOM_NAME
;

select *
from user_account;


-- 등록된 예약 오픈 목록 조회
SELECT RO.RES_OPEN_ID
, R.CAFE_ID, C.CAFE_NAME
, RO.ROOM_ID, R.ROOM_NAME
, TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD HH24:MI') AS OPEN_AT
FROM RES_OPEN RO
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
    JOIN CAFE C
    ON R.CAFE_ID = C.CAFE_ID
WHERE R.CAFE_ID IN(
    SELECT DISTINCT CAFE_ID
    FROM VW_CAFE_ROOM_INFO
    WHERE CAFE_OWNER = 15 OR CAFE_MANAGER= 15 
) 
AND RO.RES_OPEN_ID NOT IN (SELECT RES_OPEN_ID FROM RES_DROP)
--AND TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') = '2026-07-19'
--AND R.CAFE_ID = 1
ORDER BY CAFE_ID ASC, ROOM_ID ASC, OPEN_AT DESC
;

SELECT *
FROM RES_DROP;

SELECT RO.RES_OPEN_ID, R.CAFE_ID, R.ROOM_ID
, TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') AS OPEN_AT
FROM RES_OPEN RO
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
WHERE RO.RES_OPEN_ID NOT IN 
    (SELECT RES_OPEN_ID FROM RES_DROP)
AND R.CAFE_ID = 1
--AND TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') = '2026-07-19' 
ORDER BY CAFE_ID ASC, ROOM_ID ASC, OPEN_AT DESC;


-- 예약 오픈 등록 데이터 개수 
SELECT COUNT(*)
FROM RES_OPEN RO
    JOIN ROOM R
    ON RO.ROOM_ID = R.ROOM_ID
WHERE RO.RES_OPEN_ID NOT IN 
    (SELECT RES_OPEN_ID FROM RES_DROP)
AND R.CAFE_ID IN (
                    SELECT DISTINCT CAFE_ID
                    FROM VW_CAFE_ROOM_INFO
                    WHERE CAFE_OWNER = 15 OR CAFE_MANAGER = 15
                 )   
AND R.CAFE_ID = 1
AND TO_CHAR(RO.OPEN_AT, 'YYYY-MM-DD') = '2026-07-19' ;



-- 카페운영자 
-- 카페의 예약 현황 목록

-- 예약번호, 카페명, 테마명, 예약일, 예약자명, 예약자 연락처, 예약 인원 수
SELECT CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
, RESERVATION_ID
, LEADER_ID AS BOOKER_ID, LEADER_NAME AS BOOKER_NAME, LEADER_PHONE AS BOOKER_TEL
, TOTAL_MEMBER
FROM VW_RES_OPEN_BOOKED
WHERE CAFE_ID = 4
ORDER BY OPEN_AT
;

-- 카페 예약 목록 조회
-- 룸아이디로 조회
SELECT CAFE_ID, CAFE_NAME, ROOM_ID, ROOM_NAME, RES_OPEN_ID, OPEN_AT
, RESERVATION_ID
FROM VW_RES_OPEN_BOOKED
WHERE ROOM_ID = 11
ORDER BY OPEN_AT
;

-- 카페 예약 상세 조회
SELECT PARTY_ID, PARTY_NAME
, LEADER_ID, LEADER_NAME, LEADER_PHONE
, TOTAL_MEMBER
, RESERVATION_ID
FROM VW_RES_OPEN_BOOKED
WHERE RESERVATION_ID = 13


SELECT *
FROM VW_RES_OPEN_BOOKED;









